CREATE SEQUENCE equipment_seq START 1;

CREATE TABLE equipments(
  id BIGINT NOT NULL DEFAULT nextval('equipment_seq'),
  name CHARACTER VARYING(255) NOT NULL,
  code CHARACTER VARYING(255) NOT NULL unique,
  mabec_code CHARACTER VARYING(255) NOT NULL,
  protection_type CHARACTER VARYING(255) NOT NULL,
  size CHARACTER VARYING(255) NOT NULL,
  sex CHARACTER VARYING(255) NOT NULL,
  CONSTRAINT equipment_pkey PRIMARY KEY(id)
);