ALTER TABLE employees ADD COLUMN helmet_size CHARACTER VARYING(255);
ALTER TABLE employees ADD COLUMN clothing_size CHARACTER VARYING(255);
ALTER TABLE employees ADD COLUMN footwear_size CHARACTER VARYING(255);

