version: '2'
volumes:
  eipl_db:
    driver: convoy-gluster
services:
  eipl:
    image: nexus.esolutions.ro/internship/eipl:$bamboo_deploy_release
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/eipl
      SPRING_DATASOURCE_USERNAME: eipl
      SPRING_DATASOURCE_PASSWORD: eipl
      JAVA_OPTS: -Xms512m -Xmx1024m -XX:MaxMetaspaceSize=124m -Djava.security.egd=file:/dev/./urandom
      APP_ENV: integration
    links:
    - db:db
    labels:
      traefik.frontend.rule: Host:eipl.dev.esolutions.ro
      traefik.port: '8080'
      traefik.enable: 'true'
      io.rancher.container.pull_image: always
    depends_on:
    - db
  db:
    image: postgres:10.5-alpine
    environment:
      POSTGRES_DB: eipl
      POSTGRES_USER: eipl
      POSTGRES_PASSWORD: eipl
    volumes:
    - eipl_postgres_db:/var/lib/postgresql/data